export { default as Content } from './components/Content.svelte';
export { default as Course } from './components/Course.svelte';
export { default as FeaturedCourses } from './components/FeaturedCourses.svelte';
export { default as FeaturedSnacks } from './components/FeaturedSnacks.svelte';
export { default as FeaturedTutorials } from './components/FeaturedTutorials.svelte';
export { default as Header } from './components/Header.svelte';
export { default as Nav } from './components/Nav.svelte';
export { default as Hero } from './components/Hero.svelte';
export { default as Snack } from './components/Snack.svelte';
export { default as Tutorial} from './components/Tutorial.svelte';
export { default as TableOfContents } from './components/TableOfContents.svelte';

export { default as AboutPage } from './pages/AboutPage.svelte';
export { default as CoursePage } from './pages/CoursePage.svelte';
export { default as CoursesPage } from './pages/CoursesPage.svelte';
export { default as IndexPage } from './pages/IndexPage.svelte';
export { default as LoginPage } from './pages/LoginPage.svelte';
export { default as SignupPage } from './pages/SignupPage.svelte';
export { default as SnackPage } from './pages/SnackPage.svelte';
export { default as SnacksPage } from './pages/SnacksPage.svelte';
export { default as TutorialPage } from './pages/TutorialPage.svelte';
export { default as TutorialsPage } from './pages/TutorialsPage.svelte';